name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Prepare site directory
        run: |
          # Create _site directory
          mkdir -p _site
          # Copy index.html to root
          cp site/index.html _site/
          # Copy all assets
          cp -r site/assets _site/
          # Copy all images
          cp site/*.png _site/ 2>/dev/null || true
          cp site/*.jpg _site/ 2>/dev/null || true
          # List contents to verify
          echo "Contents of _site:"
          ls -la _site/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
